export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTIONS";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const GET_TOTAL_INCOME = "GET_TOTAL_INCOME";
export const GET_USER_INFO = "GET_USER_INFO";
